apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: ${{ values.name  }}
  namespace: gloo-mesh
spec:
  workloadClusters:
  - name: '*'
    namespaces:
    - name: ${{ values.name }}
    - name: ${{ values.name + "-config" }}