apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: servicedeploy
  title: Create A Service Deployment
  description: Creating a Service Deployment
spec:
  owner: group:platform
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Create a Service Deployment
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name 
          ui:autofocus: true
          ui:options:
            rows: 5
        workspace:
          title: Workspace
          type: string
          description: Workspace name 
          ui:autofocus: true
          ui:options:
            rows: 5
        repo_url:
          title: Repo URL 
          type: string
          description: Repo URL 
          ui:autofocus: true
          ui:options:
            rows: 5            

  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
          workspace: ${{ parameters.workspace }}
          repo_url: ${{ parameters.repo_url }}

    # This step publishes the contents of the working directory to GitHub.
    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        allowedHosts: ['github.com']
        description: Adding Service Deployment ${{ parameters.name }}
        repoUrl: github.com?repo=aoa-catalog&owner=solo-io
        targetPath: idp-project/workspaces/${{ parameters.workspace }}/apps/${{ parameters.name}}
        branchName: workspace_${{ parameters.workspace }}_app_${{ parameters.name }}
        title: Adding Service Deployment for ${{ parameters.name }}
        targetBranchName: glooplatform.com-2.4.x

    # The final step is to register our new component in the catalog.
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: https://github.com/solo-io/aoa-catalog/blob/workspace_${{ parameters.workspace }}_app_${{ parameters.name }}
        catalogInfoPath: /idp-project/workspaces/${{ parameters.workspace }}/apps/${{ parameters.name}}/catalog-info.yaml

  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: Review and approve the following PR
        url: ${{ steps.publish.output.remoteUrl }}